{{- range $clusterName, $cluster := .Values.clusters }}
{{- if $cluster.enabled }}
{{- if $cluster.backup }}
{{- if $cluster.backup.enabled }}
{{- if $cluster.backup.s3 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $clusterName }}-backup-creds
  labels:
    {{- include "cnpg-databases.labels" $ | nindent 4 }}
    cnpg.io/cluster: {{ $clusterName }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ $cluster.backup.s3.accessKeyId | required (printf "backup.s3.accessKeyId is required for cluster %s" $clusterName) }}
  AWS_SECRET_ACCESS_KEY: {{ $cluster.backup.s3.secretAccessKey | required (printf "backup.s3.secretAccessKey is required for cluster %s" $clusterName) }}
  {{- if $cluster.backup.s3.region }}
  AWS_DEFAULT_REGION: {{ $cluster.backup.s3.region }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}