{{- range $clusterName, $cluster := .Values.clusters }}
{{- if $cluster.enabled }}
{{- if $cluster.databases }}
{{- range $cluster.databases }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ $clusterName }}-{{ include "cnpg-database-manager.sanitizeName" .name }}
  labels:
    {{- include "cnpg-databases.labels" $ | nindent 4 }}
    cnpg.io/cluster: {{ $clusterName }}
    cnpg.io/database: {{ .name }}
spec:
  cluster:
    name: {{ $clusterName }}
  name: {{ .name }}
  owner: {{ .owner }}
  {{- if .encoding }}
  encoding: {{ .encoding }}
  {{- end }}
  {{- if .locale }}
  locale: {{ .locale }}
  {{- end }}
  {{- if .extensions }}
  extensions:
  {{- range .extensions }}
  - name: {{ .name }}
    {{- if .version }}
    version: {{ .version | quote }}
    {{- end }}
    {{- if .schema }}
    schema: {{ .schema }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}