{{- range $catalogName, $catalog := .Values.imageCatalogs }}
{{- if $catalog.enabled }}
---
apiVersion: postgresql.cnpg.io/v1
kind: {{ $catalog.kind | default "ImageCatalog" }}
metadata:
  name: {{ $catalogName }}
  {{- if ne ($catalog.kind | default "ImageCatalog") "ClusterImageCatalog" }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
  labels:
    {{- include "cnpg-databases.labels" $ | nindent 4 }}
    {{- with $catalog.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $catalog.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  images:
    {{- range $catalog.images }}
    - major: {{ .major }}
      image: {{ .image }}
    {{- end }}
{{- end }}
{{- end }}
