{{- range $clusterName, $cluster := .Values.clusters }}
{{- if $cluster.enabled }}
{{- if $cluster.databases }}
{{- range $database := $cluster.databases }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $clusterName }}-{{ $database.owner }}-password
  labels:
    {{- include "cnpg-databases.labels" $ | nindent 4 }}
    cnpg.io/cluster: {{ $clusterName }}
    cnpg.io/role: {{ $database.owner }}
type: Opaque
data:
  password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}