{{- range $clusterName, $cluster := .Values.clusters }}
{{- if $cluster.enabled }}
{{- if $cluster.databases }}
{{- $uniqueOwners := dict }}
{{- range $database := $cluster.databases }}
{{- $_ := set $uniqueOwners $database.owner true }}
{{- end }}
{{- range $owner, $_ := $uniqueOwners }}
{{- $secretName := printf "%s-%s-password" $clusterName (include "cnpg-database-manager.sanitizeName" $owner) }}
{{- $existingSecret := lookup "v1" "Secret" $.Release.Namespace $secretName }}
{{- $password := "" }}
{{- if $existingSecret }}
{{- $password = index $existingSecret.data "password" }}
{{- else }}
{{- $password = randAlphaNum 32 | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "cnpg-databases.labels" $ | nindent 4 }}
    cnpg.io/cluster: {{ $clusterName }}
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
data:
  username: {{ $owner | b64enc | quote }}
  password: {{ $password | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
