apiVersion: v2
name: roundcube
description: A free and open source webmail solution with a desktop-like user interface
type: application
version: 0.7.0
appVersion: "1.6.11"
keywords:
  - roundcube
  - webmail
  - email
  - mail
home: https://github.com/encircle360-oss/helm-charts/tree/main/charts/roundcube
sources:
  - https://github.com/roundcube/roundcubemail
  - https://github.com/encircle360-oss/helm-charts
maintainers:
  - name: encircle360-oss
    email: oss@encircle360.com
icon: https://raw.githubusercontent.com/roundcube/roundcubemail/master/skins/elastic/images/logo.svg
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - kind: changed
      description: "BREAKING: Simplified plugin config architecture - removed init containers and postStart hooks"
    - kind: changed
      description: Plugin configs now mounted directly via ConfigMaps (no timing issues or race conditions)
    - kind: changed
      description: Secrets now provided via standard Kubernetes environment variables using getenv() in PHP
    - kind: removed
      description: Removed pluginSecrets and pluginSecretsExistingSecret (use extraEnvVars instead)
    - kind: removed
      description: Removed pluginConfigHookTimeout (no longer needed without hooks)
    - kind: changed
      description: Each plugin config gets its own ConfigMap for better isolation and debugging
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/bitnami/postgresql
    - url: https://artifacthub.io/packages/helm/bitnami/mariadb
