apiVersion: v2
name: roundcube
description: A free and open source webmail solution with a desktop-like user interface
type: application
version: 0.8.1
appVersion: "1.6.11"
keywords:
  - roundcube
  - webmail
  - email
  - mail
home: https://github.com/encircle360-oss/helm-charts/tree/main/charts/roundcube
sources:
  - https://github.com/roundcube/roundcubemail
  - https://github.com/encircle360-oss/helm-charts
maintainers:
  - name: encircle360-oss
    email: oss@encircle360.com
icon: https://raw.githubusercontent.com/roundcube/roundcubemail/master/skins/elastic/images/logo.svg
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - kind: fixed
      description: CRITICAL - Plugin configs now mounted to temp location to prevent blocking Composer extraction
    - kind: fixed
      description: Restored v0.3.3 working implementation with postStart hook for config copying after Composer
    - kind: changed
      description: Reverted from direct plugin directory mounts back to temp mounts + lifecycle hook pattern
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/bitnami/postgresql
    - url: https://artifacthub.io/packages/helm/bitnami/mariadb
