apiVersion: v2
name: cnpg-database-manager
description: Multi-database and multi-tenant management for CloudNativePG clusters with automatic secret generation and isolation
type: application
version: 0.1.2
appVersion: "1.0"
keywords:
  - postgresql
  - database
  - cloudnative-pg
  - cnpg
  - multi-tenant
home: https://github.com/encircle360-oss/helm-charts/tree/main/charts/cnpg-database-manager
sources:
  - https://github.com/encircle360-oss/helm-charts
  - https://cloudnative-pg.io/
maintainers:
  - name: encircle360-oss
    email: oss@encircle360.com
icon: https://avatars.githubusercontent.com/u/100373852
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - kind: added
      description: Add comprehensive values.schema.json for validation
    - kind: added
      description: Add detailed values documentation with all configuration parameters
    - kind: changed
      description: Improve values.yaml with extensive inline documentation
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg