name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'
      - 'README.md'
      - 'artifacthub-repo.yml'
      - 'charts/**/README.md.gotmpl'
      - 'charts/**/README.md'
      - 'charts/**/Chart.yaml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs dependencies
        run: |
          pip install -r requirements.txt

      - name: Build MkDocs documentation
        run: |
          mkdocs build -d site

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages

      - name: Copy docs to gh-pages /docs folder
        run: |
          # Remove old docs but keep chart packages and index.yaml
          rm -rf docs/
          mkdir -p docs/
          # Copy new docs
          cp -r site/* docs/
          
      - name: Copy artifacthub-repo.yml to root
        run: |
          git checkout main -- artifacthub-repo.yml
          
      - name: Commit and push docs
        run: |
          git add docs/ artifacthub-repo.yml
          git commit -m "docs: update documentation" || echo "No changes to commit"
          git push origin gh-pages