name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.16.3

      - name: Add dependency repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs dependencies
        run: |
          pip install -r requirements.txt

      - name: Build chart packages
        run: |
          mkdir -p .deploy
          for chart in charts/*/; do
            if [ -f "${chart}Chart.yaml" ]; then
              helm dependency build "$chart"
              helm package "$chart" -d .deploy
            fi
          done

      - name: Fetch existing index.yaml from gh-pages
        run: |
          # Download existing index.yaml if it exists
          curl -sL https://${{ github.repository_owner }}.github.io/helm-charts/index.yaml -o .deploy/index.yaml || echo "No existing index.yaml found"
      
      - name: Create/merge index.yaml
        run: |
          # Merge with existing index if present, otherwise create new
          helm repo index .deploy --url https://${{ github.repository_owner }}.github.io/helm-charts/ --merge .deploy/index.yaml

      - name: Build MkDocs documentation
        run: |
          mkdocs build -d .deploy-docs

      - name: Merge Helm packages and docs
        run: |
          mv .deploy-docs/* .deploy/
          rm -rf .deploy-docs
          # Copy artifacthub-repo.yml for ArtifactHub discovery
          cp artifacthub-repo.yml .deploy/
          
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: '.deploy'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4